### ISSUE TITLE
Edit Farmer

### ISSUE THREAD

**Issue by Nanzala** [Ghalani/alsa#1]
http://app.ghalani.com/organizations/2/farmers/1

When I click the 'Pencil' edit button, it takes me to a pop-up form to fill. After filling the form and click on 'Create Farmer' button (this should instead be 'Edit Farmer'), I get an error message 'We're sorry but something went wrong'.

**Comment by darlingtonamz** [comment]
I found the error on the console
`NoMethodError (undefined method `farmer_url' for #<FarmersController:0x007f9001230238>):
2016-11-10T11:42:38.272850+00:00 app[web.1]:   app/controllers/farmers_controller.rb:69:in `block (2 levels) in update'
2016-11-10T11:42:38.272853+00:00 app[web.1]:   app/controllers/farmers_controller.rb:67:in `update'`
I'll start working on it
